
</main>
<footer class="page-footer main-color">
<div class="container">
<div class="row">
  <div class="col l12">
	<h5 class="white-text">Resabike</h5>
	<p class="grey-text text-lighten-4">Postbus</p>
  </div>
</div>
</div>
<div class="footer-copyright">
<div class="container">
© <?php echo date("Y"); ?> Mikko & Ibrahim
</div>
</div>
</footer>



	<?php //custom javascripts ?>
<script src="/<?php echo SITE_NAME; ?>/assets/js/scripts.js"></script>

</body>
</html>
